GET http://localhost:3000/nepeykozlenchikomstanish

###

POST http://localhost:3000/nepeykozlenchikomstanish
Content-Type: application/json

{
	"alias": "alf",
    "tipContent": "If you are even remotely thinking about studying abroad, go get your passport renewed or get one if you don’t have one. It will save you lots of time in the future.",
    "tags": ["school"],
    "isLive": "true"
}

###

GET http://localhost:3000/nepeykozlenchikomstanish/5e48ca8a030eeb1d96b2069a

###

DELETE http://localhost:3000/nepeykozlenchikomstanish/5e48ce3350e3721ebaec3a4c

###

PATCH http://localhost:3000/nepeykozlenchikomstanish/5e4ba05451731b67faeafc50
Content-Type: application/json

{
	"newTags": [
      "money"
    ],
    "newAlias": "John",
    "newTipContent": "You don't have to spend your dining dollars at ACAC, you can also buy food in bulk through the library catalog.",
    "newTimestamp": "2020-02-07T08:29:08.934Z",
    "newIsLive": true
}