GET http://utulsa-tips-api.herokuapp.com/nepeykozlenchikomstanish

###

POST http://utulsa-tips-api.herokuapp.com/nepeykozlenchikomstanish
Content-Type: application/json

{
	"alias": "someone",
    "tipContent": "do this do that",
    "tags": ["$$$", "School", "Orgs"],
    "isLive": "false"
}

###

GET http://utulsa-tips-api.herokuapp.com/nepeykozlenchikomstanish/5e48ca8a030eeb1d96b2069a

###

DELETE http://utulsa-tips-api.herokuapp.com/nepeykozlenchikomstanish/5e48ca8a030eeb1d96b2069a

###

PATCH http://utulsa-tips-api.herokuapp.com/nepeykozlenchikomstanish/5e4a0c647c70e00017cc8e79
Content-Type: application/json

{
	"newAlias": "anybody",
    "newTipContent": "this is my advice",
    "newTags": ["money", "school", "fun"],
    "newIsLive": "true"
}