GET http://utulsa-tips-api.herokuapp.com/tips

###

POST http://utulsa-tips-api.herokuapp.com/tips
Content-Type: application/json

{
	"alias": "Schnitzel",
    "tipContent": "vas is guuut ya",
    "tags": ["$$$", "School"],
    "isLive": "false"
}

###

GET http://utulsa-tips-api.herokuapp.com/tips/5e489d9d7ab561165606d621

###

DELETE http://utulsa-tips-api.herokuapp.com/tips/5e489d9d7ab561165606d621

###

PATCH http://utulsa-tips-api.herokuapp.com/tips/5e489fb43edcd416d6487b74
Content-Type: application/json

{
	"alias": "Anonymous",
    "newTipContent": "YET AGAIN UPDATED tip content",
    "newTags": ["$$$", "Fun"],
    "newIsLive": "true"
}

