GET http://localhost:3000/tips

###

POST http://localhost:3000/tips
Content-Type: application/json

{
	"alias": "KKAAPPAA WASAO WASAP",
    "tipContent": "another sample tip content",
    "tags": ["$$$", "School"],
    "isLive": "false"
}

###

GET http://localhost:3000/tips/5e48cb66030eeb1d96b2069c

###

DELETE http://localhost:3000/tips/5e489d3d7ab561165606d620

###

PATCH http://localhost:3000/tips/5e489d3d7ab561165606d620
Content-Type: application/json

{
	"newAlias": "Anonymous",
    "newTipContent": "OK SO THIS TIME IT HAS TO WORK tip content",
    "newTags": ["$$$", "School"],
    "newIsLive": "true"
}