GET http://localhost:3000/tips

###

POST http://localhost:3000/tips
Content-Type: application/json

{
	"alias": "Anonymous",
    "tipContent": "another sample tip content",
    "tags": ["$$$", "School"],
    "isLive": "false"
}

###

GET http://localhost:3000/tips/5e489d9d7ab561165606d621

###

DELETE http://localhost:3000/tips/5e489d9d7ab561165606d621

###

PATCH http://localhost:3000/tips/5e489fb43edcd416d6487b74
Content-Type: application/json

{
	"newAlias": "Anonymous",
    "newTipContent": "OK SO THIS TIME IT HAS TO WORK tip content",
    "newTags": ["$$$", "School"],
    "newIsLive": "true"
}