GET http://utulsa-tips-api.herokuapp.com/tips

###

POST http://utulsa-tips-api.herokuapp.com/tips
Content-Type: application/json

{
	"alias": "UNMISTAKEABLE",
    "tipContent": "UNMISTAKEABLE CONTENT",
    "tags": ["$$$", "School", "Fun"],
    "isLive": "true"
}

###

GET http://utulsa-tips-api.herokuapp.com/tips/5e48aae82b271900179a9702

###

DELETE http://utulsa-tips-api.herokuapp.com/tips/5e48aae82b271900179a9702

###

PATCH http://utulsa-tips-api.herokuapp.com/tips/5e48aae82b271900179a9702
Content-Type: application/json

{
	"alias": "UPDATED UNMISTAKEABLE",
    "newTipContent": "UNMISTAKABLY EDITED",
    "newTags": ["$$$", "Fun"],
    "newIsLive": "false"
}

